// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXRfnTt-7pAzQImayOKq1XeWUwIuPmw6U',
    appId: '1:829982880892:web:68350017c524a1a3fa45f9',
    messagingSenderId: '829982880892',
    projectId: 'lab8-e14e1',
    authDomain: 'lab8-e14e1.firebaseapp.com',
    storageBucket: 'lab8-e14e1.firebasestorage.app',
    measurementId: 'G-JZJ77NTS78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1N4EgRxwFXIOtxcgjsxk2vdUjC8wQYlM',
    appId: '1:829982880892:android:ad8f7ff38c48ff9dfa45f9',
    messagingSenderId: '829982880892',
    projectId: 'lab8-e14e1',
    storageBucket: 'lab8-e14e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbCXz4FFyJeJIuxo6z1z_Pt-CvvSsIpvo',
    appId: '1:829982880892:ios:ed991c6c9cf78d8cfa45f9',
    messagingSenderId: '829982880892',
    projectId: 'lab8-e14e1',
    storageBucket: 'lab8-e14e1.firebasestorage.app',
    iosClientId: '829982880892-qtlf92tuj404n7l90afnlgdr810mn9vv.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab8043',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbCXz4FFyJeJIuxo6z1z_Pt-CvvSsIpvo',
    appId: '1:829982880892:ios:ed991c6c9cf78d8cfa45f9',
    messagingSenderId: '829982880892',
    projectId: 'lab8-e14e1',
    storageBucket: 'lab8-e14e1.firebasestorage.app',
    iosClientId: '829982880892-qtlf92tuj404n7l90afnlgdr810mn9vv.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab8043',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXRfnTt-7pAzQImayOKq1XeWUwIuPmw6U',
    appId: '1:829982880892:web:0762f269bbbfac42fa45f9',
    messagingSenderId: '829982880892',
    projectId: 'lab8-e14e1',
    authDomain: 'lab8-e14e1.firebaseapp.com',
    storageBucket: 'lab8-e14e1.firebasestorage.app',
    measurementId: 'G-2BE19ZHH47',
  );
}
